//
//  Language.swift
//  Themis
//
//  Created by Tom Rudnick on 23.01.23.
//
// swiftlint:disable identifier_name

import Foundation

public enum Language: String {
    case swift
    case python
    case c
    case rust
    case java
    case gradle
    case bash
    case javascript
    case dart
    case groovy
    case haskell
    case kotlin
    case scala
    case typescript
    case r
    case rspec
    case ruby
    case rubymine
    case sass
    case spring
    case sqlalchemy
    case sqlite
    case ssh
    case svelte
    case tailwindcss
    case tensorflow
    case terraform
    case threejs
    case travis
    case typo3
    case uwsgi
    case vscode
    case vuejs
    case webpack
    case xcode
    case yarn
    case arduino
    case ansible
    case cmake
    case coffeescript
    case css3
    case docker
    case eslint
    case express
    case fastapi
    case flask
    case flutter
    case gcc
    case git
    case go
    case godot
    case graphql
    case grunt
    case gulp
    case html5
    case intellij
    case jasmine
    case jest
    case jquery
    case julia
    case jupyter
    case latex
    case lua
    case markdown
    case matlab
    case mongodb
    case mysql
    case nginx
    case nodejs
    case npm
    case numpy
    case objectivec
    case ocaml
    case opencv
    case opengl
    case oracle
    case perl
    case php
    case postgresql
    case processing
    case pytest
    case pytorch
    case rails
    case react
    case redis
    case redux
    case rstudio
}
