name: SwiftLint

on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Swift environment
        uses: sinoru/actions-setup-swift@v2
      - name: Run SwiftLint
        uses: sinoru/actions-swiftlint@v6
        with:
          swiftlint-args: --config swiftlint.yml --strict
